#!/bin/bash
# unraid-stats.sh - Unraid-specific sensor collector for the aoostar-lcd
# "Unraid Dark" panel.
#
# Reads aster-sysinfo's output plus Unraid's own disk state
# (/var/local/emhttp/disks.ini - temperatures cached by emhttp, so spun-down
# disks are NEVER woken) and writes panel-ready values to
# $RUNDIR/sensors/unraid.txt (atomic rename).
#
# Dynamic colors: each colored value has three label "slots" (_g/_a/_r);
# the value is written under exactly one of them per cycle and asterctl
# skips labels that have no value - so the on-screen color follows the
# thresholds below.
#
# Configuration comes from the environment (set by rc.aoostar-lcd):
#   NETIF REFRESH CPU_TEMP_WARN CPU_TEMP_HOT HDD_HOT SSD_HOT CPU_TEMP_SENSOR

RUNDIR="${RUNDIR:-/run/aoostar-lcd}"
SYSINFO="$RUNDIR/sensors/sysinfo.txt"
OUT="$RUNDIR/sensors/unraid.txt"
TMP="$RUNDIR/.unraid.txt.tmp"
DISKS_INI="${DISKS_INI:-/var/local/emhttp/disks.ini}"

NETIF="${NETIF:-br0}"
REFRESH="${REFRESH:-3}"
CPU_TEMP_WARN="${CPU_TEMP_WARN:-70}"
CPU_TEMP_HOT="${CPU_TEMP_HOT:-85}"
UTIL_WARN="${UTIL_WARN:-70}"
UTIL_HOT="${UTIL_HOT:-90}"
HDD_HOT="${HDD_HOT:-45}"
SSD_HOT="${SSD_HOT:-60}"
CPU_TEMP_SENSOR="${CPU_TEMP_SENSOR:-auto}"

# slot: <label> <value> <warn> <hot>  ->  emits label_g/_a/_r line
slot() {
  local label="$1" value="$2" warn="$3" hot="$4" int
  [ -z "$value" ] && return
  int=${value%%.*}
  if [ "$int" -ge "$hot" ] 2>/dev/null; then
    echo "${label}_r: $value"
  elif [ "$int" -ge "$warn" ] 2>/dev/null; then
    echo "${label}_a: $value"
  else
    echo "${label}_g: $value"
  fi
}

cpu_temp_from_hwmon() {
  # fallback: read k10temp (AMD) / coretemp (Intel) directly from sysfs
  local hw name t
  for hw in /sys/class/hwmon/hwmon*; do
    name=$(cat "$hw/name" 2>/dev/null)
    case "$name" in
      k10temp|coretemp|zenpower)
        t=$(cat "$hw"/temp1_input 2>/dev/null)
        [ -n "$t" ] && echo $((t / 1000)) && return
        ;;
    esac
  done
}

while :; do
  # ---- read aster-sysinfo values into S[] -------------------------------
  unset S; declare -A S
  if [ -f "$SYSINFO" ]; then
    while IFS=: read -r key val; do
      [ -z "$key" ] || [ "${key:0:1}" = "#" ] && continue
      key="${key#"${key%%[![:space:]]*}"}"; key="${key%"${key##*[![:space:]]}"}"
      val="${val#"${val%%[![:space:]]*}"}"; val="${val%"${val##*[![:space:]]}"}"
      S[$key]="$val"
    done < "$SYSINFO"
  fi

  # ---- CPU temperature source ------------------------------------------
  cputemp=""
  if [ "$CPU_TEMP_SENSOR" != "auto" ]; then
    cputemp="${S[$CPU_TEMP_SENSOR]}"
  else
    for k in temperature_cpu temperature_k10temp_Tctl temperature_k10temp \
             temperature_Tctl temperature_coretemp_Package_id_0; do
      [ -n "${S[$k]}" ] && cputemp="${S[$k]}" && break
    done
    if [ -z "$cputemp" ]; then
      for k in "${!S[@]}"; do
        case "$k" in
          temperature_*k10temp*|temperature_*coretemp*|temperature_*Tctl*)
            [ "${k%"#unit"}" = "$k" ] && cputemp="${S[$k]}" && break ;;
        esac
      done
    fi
    [ -z "$cputemp" ] && cputemp=$(cpu_temp_from_hwmon)
  fi

  # ---- GPU utilization (amdgpu iGPU, same die as CPU) -------------------
  gpuutil=""
  for f in /sys/class/drm/card*/device/gpu_busy_percent; do
    [ -f "$f" ] && gpuutil=$(cat "$f" 2>/dev/null) && break
  done

  # ---- disks: temperatures from emhttp (never wakes disks) --------------
  hdd_max=0 ssd_max=0 hdd_n=0 ssd_n=0 standby=0 hot_list=""
  if [ -f "$DISKS_INI" ]; then
    dname="" dev="" temp=""
    flush_disk() {
      [ -z "$dev" ] && return
      case "$dname" in flash|"") dev=""; return ;; esac
      if [ "$temp" = "*" ] || [ -z "$temp" ]; then
        standby=$((standby + 1)); dev=""; return
      fi
      local is_ssd=0 limit
      case "$dev" in nvme*) is_ssd=1 ;; *)
        [ "$(cat /sys/block/$dev/queue/rotational 2>/dev/null)" = "0" ] && is_ssd=1 ;;
      esac
      if [ "$is_ssd" = "1" ]; then
        ssd_n=$((ssd_n + 1)); [ "$temp" -gt "$ssd_max" ] && ssd_max=$temp
        limit=$SSD_HOT
      else
        hdd_n=$((hdd_n + 1)); [ "$temp" -gt "$hdd_max" ] && hdd_max=$temp
        limit=$HDD_HOT
      fi
      if [ "$temp" -ge "$limit" ] 2>/dev/null; then
        hot_list="$hot_list, $dname ${temp}°C"
      fi
      dev=""
    }
    while IFS= read -r line; do
      case "$line" in
        \[*\])   flush_disk; dname="${line#[\"}"; dname="${dname%\"]}"
                 dname="${dname#[}"; dname="${dname%]}"; dev=""; temp="" ;;
        device=*) dev="${line#device=}"; dev="${dev//\"/}" ;;
        temp=*)   temp="${line#temp=}"; temp="${temp//\"/}" ;;
      esac
    done < "$DISKS_INI"
    flush_disk
  fi
  hot_list="${hot_list#, }"

  # ---- write panel sensor file ------------------------------------------
  {
    echo "# generated by unraid-stats.sh"
    # static captions (rendered by asterctl as plain text sensors)
    echo "lbl_cpu: CPU / GPU"
    echo "lbl_cpu_cap: CPU"
    echo "lbl_gpu_cap: GPU"
    echo "lbl_ram: RAM"
    echo "lbl_net: NETWORK"
    echo "lbl_up: ▲"
    echo "lbl_down: ▼"
    echo "lbl_ip: IP"

    slot cpu_util "${S[cpu_usage_percent]%%.*}" "$UTIL_WARN" "$UTIL_HOT"
    slot gpu_util "${gpuutil%%.*}" "$UTIL_WARN" "$UTIL_HOT"
    slot cpu_temp "${cputemp%%.*}" "$CPU_TEMP_WARN" "$CPU_TEMP_HOT"
    [ -n "${S[mem_usage_percent]}" ] && echo "mem_pct: ${S[mem_usage_percent]%%.*}"

    u="network_${NETIF}_upload_speed"; uu="${u}#unit"
    d="network_${NETIF}_download_speed"; du="${d}#unit"
    if [ -n "${S[$u]}" ]; then
      echo "net_up: ${S[$u]}"
      [ -n "${S[$uu]}" ] && echo "net_up#unit: ${S[$uu]}"
    fi
    if [ -n "${S[$d]}" ]; then
      echo "net_down: ${S[$d]}"
      [ -n "${S[$du]}" ] && echo "net_down#unit: ${S[$du]}"
    fi
    ip="${S[network_${NETIF}_address0]}"
    [ -n "$ip" ] && echo "net_ip: ${ip%/*}"

    if [ -n "$hot_list" ]; then
      echo "disk_alert: ⚠ DISK HOT: $hot_list"
    else
      summary=""
      [ "$hdd_n" -gt 0 ] && summary="HDD max ${hdd_max}°C"
      [ "$ssd_n" -gt 0 ] && summary="${summary:+$summary   ·   }SSD max ${ssd_max}°C"
      [ "$standby" -gt 0 ] && summary="${summary:+$summary   ·   }$standby standby"
      echo "disk_ok: ${summary:-disks: no data}"
    fi
  } > "$TMP"
  mv -f "$TMP" "$OUT"

  sleep "$REFRESH"
done
