#!/usr/bin/env python3
"""Assemble the self-contained aoostar-lcd.plg Unraid plugin from src files.

Every payload file is embedded inline (CDATA), so the plugin reinstalls
itself at every boot from the flash drive without needing internet access
(the asterctl binary package is cached on flash separately).
"""
import base64
import hashlib
import os
import sys

SRC = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(SRC), 'aoostar-lcd.plg')
ROOT = os.path.join(SRC, 'plugin-root')
DEST = '/usr/local/emhttp/plugins/aoostar-lcd'

VERSION = '2026.07.18b'

# (relative path in plugin-root, mode)
PAYLOAD = [
    ('scripts/rc.aoostar-lcd', '0755'),
    ('scripts/unraid-stats.sh', '0755'),
    ('AOOSTARLCD.page', '0644'),
    ('include/exec.php', '0644'),
    ('sensor-mapping.template', '0644'),
    ('panel/monitor.json', '0644'),
    ('README.md', '0644'),
]

# binary payload files, embedded base64 (relative path, mode)
PAYLOAD_BIN = [
    ('panel/unraid-dark.png', '0644'),
]


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def cdata(text):
    # the plugin manager reads content from an <INLINE> child element
    # (see file_component() in dynamix.plugin.manager/scripts/plugin)
    if ']]>' in text:
        sys.exit(f'CDATA terminator found in payload - cannot embed: {text[:80]}')
    return f'<INLINE>\n<![CDATA[\n{text}]]>\n</INLINE>'


def main():
    # icon is generated by make_icon.py; embed as base64 inside install.sh
    icon_path = os.path.join(ROOT, 'images', 'aoostar-lcd.png')
    if not os.path.exists(icon_path):
        sys.exit('icon missing - run make_icon.py first')
    icon_b64 = base64.b64encode(open(icon_path, 'rb').read()).decode()
    icon_b64 = '\n'.join(icon_b64[i:i + 76] for i in range(0, len(icon_b64), 76))

    install_sh = read(os.path.join(SRC, 'install.sh')).replace('@ICON_B64@', icon_b64)
    remove_sh = read(os.path.join(SRC, 'remove.sh'))

    parts = []
    parts.append("<?xml version='1.0' standalone='yes'?>\n")
    parts.append('<!DOCTYPE PLUGIN [\n')
    parts.append('<!ENTITY name      "aoostar-lcd">\n')
    parts.append('<!ENTITY author    "miah.yap">\n')
    parts.append(f'<!ENTITY version   "{VERSION}">\n')
    parts.append(']>\n\n')
    parts.append('<PLUGIN name="&name;" author="&author;" version="&version;" '
                 'min="6.11.0" icon="aoostar-lcd.png" launch="Settings/AOOSTARLCD" '
                 'support="https://github.com/zehnm/aoostar-rs/discussions">\n\n')
    parts.append(f'''<CHANGES>
###{VERSION}
- Initial release: drive the AOOSTAR WTR MAX / GEM12+ PRO integrated
  display on Unraid using the open-source aoostar-rs driver (asterctl +
  aster-sysinfo). Includes settings page, sensor mapping generation and
  boot-time autostart.
</CHANGES>

''')

    # payload files
    for rel, mode in PAYLOAD:
        content = read(os.path.join(ROOT, rel))
        # the plugin manager writes trim(content)+"\n" and, on reinstall,
        # replaces an existing file only when its SHA256 differs
        written = content.strip() + '\n'
        sha = hashlib.sha256(written.encode()).hexdigest()
        parts.append(f'<FILE Name="{DEST}/{rel}" Mode="{mode}">\n')
        parts.append(f'<SHA256>{sha}</SHA256>\n')
        parts.append(cdata(content))
        parts.append('\n</FILE>\n\n')

    # binary payload files: written verbatim from base64, SHA256 of the
    # decoded bytes so changed files are replaced on reinstall
    for rel, mode in PAYLOAD_BIN:
        blob = open(os.path.join(ROOT, rel), 'rb').read()
        sha = hashlib.sha256(blob).hexdigest()
        b64 = base64.b64encode(blob).decode()
        b64 = '\n'.join(b64[i:i + 76] for i in range(0, len(b64), 76))
        parts.append(f'<FILE Name="{DEST}/{rel}" Mode="{mode}" Type="base64">\n')
        parts.append(f'<SHA256>{sha}</SHA256>\n')
        parts.append(f'<INLINE>\n{b64}\n</INLINE>')
        parts.append('\n</FILE>\n\n')

    # post-install script
    parts.append('<FILE Run="/bin/bash">\n')
    parts.append(cdata(install_sh))
    parts.append('\n</FILE>\n\n')

    # removal script
    parts.append('<FILE Run="/bin/bash" Method="remove">\n')
    parts.append(cdata(remove_sh))
    parts.append('\n</FILE>\n\n')

    parts.append('</PLUGIN>\n')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(''.join(parts))
    print(f'wrote {OUT} ({os.path.getsize(OUT)} bytes)')


if __name__ == '__main__':
    main()
